const getChampColor = getChampColorProp || window.getChampColor || (() => '#95a5a6');
const computeMatchStats = window.computeMatchStats;
const getMultigolRange = window.getMultigolRange;
const getBestBetForFamily = window.getBestBetForFamily;
const getPercentualeClasse = window.getPercentualeClasse;
const normalizeDate = window.normalizeDate;
const getTodayStr = window.getTodayStr;
const addDaysToDateStr = window.addDaysToDateStr;
const formatDateEU = window.formatDateEU;
const FAMIGLIE_GIOCATE = window.FAMIGLIE_GIOCATE || {};